# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main_Comentario_BB.o Persona.o
LINKOBJ  = main_Comentario_BB.o Persona.o
LIBS     = -L"C:/Dev_cpp/Dev-Cpp/MinGW64/lib" -L"C:/Dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Dev_cpp/Dev-Cpp/MinGW64/include" -I"C:/Dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Dev_cpp/Dev-Cpp/MinGW64/include" -I"C:/Dev_cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Dev_cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Ejemplo_Comentario_BB.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main_Comentario_BB.o: main_Comentario_BB.cpp
	$(CPP) -c main_Comentario_BB.cpp -o main_Comentario_BB.o $(CXXFLAGS)

Persona.o: Persona.cpp
	$(CPP) -c Persona.cpp -o Persona.o $(CXXFLAGS)
